### ISSUE TITLE
[Bug] v3.12.1 Beta - Menu Button Doesn't Exit Game in MAME2003Plus core (patched from 3.11.2)

### ISSUE THREAD

**Issue by Level99OCR** [Sichroteph/Onion#5]
### Checklist

- [X] I am reporting a bug in the Onion OS
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

3.12.1

### Miyoo Firmware Version

220204190828

### Provide a clear and concise description of the issue

It seems like all other shortcuts work except the exit game and power button in the latest beta (3.12.1) for MAME2003Plus core. I've tested a few other systems (Atari 7800, Genesis) and the shortcuts there work fine. 

### Steps to Reproduce

Pressing menu button once or twice with no other buttons pressed while in Arcade core just makes the vibration motor briefly activate. All other shortcuts work, including bringing up the Retroarch menu, which as of now is the only way to exit Arcade games.
Pressing and holding the power button to initiate suspend+power down also doesn't do anything while in Arcade games. If this is done and then the game is closed via the Retroarch menu method, then as soon as the game exits the system shuts down.

Game I was testing with was Gun.Smoke. 

### Provide any additional context or information that may help us investigate your issue

My Miyoo was on 3.11.2 and I used the patch files to upgrade instead of doing a full reinstall.

**Comment by ac3nl** [comment]
In mame try pressing menu + start simultaneously 
Now you are in the retroarch menu

Pressing menu will exit now
Pressing power will power down

seems like some games map de menubutton in the mame2003plus core, but not all games do

**Comment by Olywa** [comment]
Unfortunately Mame can be a little buggy with Onion, this is a long standing issue and there is not much we can do about it. Some cores just prevent RetroArch reacting to termination signals.

I believe this is largely because the Mame cores (and some Final Burn Cores) are emulating literally 100's of different machines (as opposed to console Cores which are emulating just one). It's also why some games will play nice (with menu shortcuts and savestates) but the majority will not.

It would require significant work by the RA Core developer (not the Onion team) which is highly unlikely. For now, as per above, the best option is to exit Mame via the RA menu with start + select.
